# Generated by Django 2.2 on 2019-06-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('ponentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('explicacion', models.TextField()),
                ('Fecha', models.DateField()),
                ('Hora_ini', models.TimeField()),
                ('Hora_fin', models.TimeField()),
                ('id_aud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencias.Auditorio')),
                ('ponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponentes.Ponente')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora_Entrada', models.TimeField(null=True)),
                ('Hora_Salida', models.TimeField(null=True)),
                ('NUA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Estudiante')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencias.Conferencia')),
            ],
        ),
        migrations.AddField(
            model_name='conferencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencias.Tipo'),
        ),
    ]
