# Generated by Django 2.2 on 2019-06-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Trayectoria', models.TextField()),
                ('edad', models.IntegerField()),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Sexo')),
            ],
        ),
    ]
